2013-12-13 14:40:33.689 [error] <0.221.0> CRASH REPORT Process <0.221.0> with 0 neighbours exited with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in gen_server:init_it/6 line 328
2013-12-13 14:40:33.690 [error] <0.217.0> Supervisor {<0.217.0>,'Elixir.Yugioh.Supervisor'} had child 'Elixir.Yugioh.Repo' started with 'Elixir.Yugioh.Repo':start_link() at undefined exit with reason no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in context start_error
2013-12-13 14:40:33.690 [error] <0.222.0> gen_server <0.222.0> terminated with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236
2013-12-13 14:40:33.690 [error] <0.222.0> CRASH REPORT Process <0.222.0> with 0 neighbours exited with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in gen_server:terminate/6 line 744
2013-12-13 14:40:33.691 [error] <0.215.0> CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Yugioh.Repo',{{badmatch,{error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}}},[{poolboy,new_worker,1,[{file,"src/poolboy.erl"},{line,236}]},{poolboy,prepopulate,3,[{file,"src/poolboy.erl"},{line,257}]},{poolboy,init,3,[{file,"src/poolboy.erl"},{line,120}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}}},{'Elixir.Yugioh',start,[normal,[]]}} in application_master:init/4 line 133
2013-12-13 14:41:24.303 [error] <0.158.0> gen_server <0.158.0> terminated with reason: {'module could not be loaded',[{'Elixir.PT11',write,[11000,[1,1]],[]},{'Elixir.Yugioh.System.Room',handle,3,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/system/room.ex"},{line,8}]},{'Elixir.Yugioh.Player',handle_call,3,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,28}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 14:41:24.304 [error] <0.158.0> CRASH REPORT Process <0.158.0> with 2 neighbours exited with reason: call to undefined function 'Elixir.PT11':write(11000, [1,1]) in gen_server:terminate/6 line 744
2013-12-13 14:41:24.304 [error] <0.137.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.157.0> exit with reason call to undefined function 'Elixir.PT11':write(11000, [1,1]) in context child_terminated
2013-12-13 15:22:51.600 [error] <0.252.0> gen_server <0.252.0> terminated with reason: no match of right hand value ok in 'Elixir.Yugioh.System.Room':handle/3 line 8
2013-12-13 15:22:51.601 [error] <0.252.0> CRASH REPORT Process <0.252.0> with 2 neighbours exited with reason: no match of right hand value ok in 'Elixir.Yugioh.System.Room':handle/3 line 8 in gen_server:terminate/6 line 744
2013-12-13 15:22:51.601 [error] <0.231.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.251.0> exit with reason no match of right hand value ok in 'Elixir.Yugioh.System.Room':handle/3 line 8 in context child_terminated
2013-12-13 15:25:39.620 [error] <0.223.0> gen_server <0.223.0> terminated with reason: no case clause matching ok in 'Elixir.Yugioh.System.Room':handle/3 line 8
2013-12-13 15:25:39.620 [error] <0.223.0> CRASH REPORT Process <0.223.0> with 2 neighbours exited with reason: no case clause matching ok in 'Elixir.Yugioh.System.Room':handle/3 line 8 in gen_server:terminate/6 line 744
2013-12-13 15:25:39.621 [error] <0.202.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.222.0> exit with reason no case clause matching ok in 'Elixir.Yugioh.System.Room':handle/3 line 8 in context child_terminated
2013-12-13 15:29:42.556 [error] <0.230.0> gen_server <0.230.0> terminated with reason: no case clause matching ok in 'Elixir.Yugioh.System.Room':handle/3 line 8
2013-12-13 15:29:42.557 [error] <0.230.0> CRASH REPORT Process <0.230.0> with 2 neighbours exited with reason: no case clause matching ok in 'Elixir.Yugioh.System.Room':handle/3 line 8 in gen_server:terminate/6 line 744
2013-12-13 15:29:42.557 [error] <0.209.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.229.0> exit with reason no case clause matching ok in 'Elixir.Yugioh.System.Room':handle/3 line 8 in context child_terminated
2013-12-13 15:34:22.647 [error] emulator Error in process <0.236.0> with exit value: {{badmatch,<<0 bytes>>},[{'Elixir.Yugioh.Proto.PT11',read,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/proto/pt_11.ex"},{line,5}]},{'Elixir.Yugioh.Acceptor.Acceptor',parse_game_packet_loop,2,[{file,"/Users/sail/elixir/yugio... 


2013-12-13 15:34:22.647 [error] <0.216.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.236.0> exit with reason no match of right hand value <<>> in 'Elixir.Yugioh.Proto.PT11':read/2 line 5 in context child_terminated
2013-12-13 15:58:02.154 [error] <0.159.0> gen_server <0.159.0> terminated with reason: bad argument in 'Elixir.Yugioh.Proto.PT11':write/2 line 19
2013-12-13 15:58:02.154 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 2 neighbours exited with reason: bad argument in 'Elixir.Yugioh.Proto.PT11':write/2 line 19 in gen_server:terminate/6 line 744
2013-12-13 15:58:02.154 [error] <0.138.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.158.0> exit with reason bad argument in 'Elixir.Yugioh.Proto.PT11':write/2 line 19 in context child_terminated
2013-12-13 16:02:53.907 [error] <0.152.0> gen_server <0.152.0> terminated with reason: bad argument in call to io:put_chars(<0.23.0>, unicode, [<<32,32,49,41,32,116,101,115,116,32,105,110,116,101,103,114,97,116,105,111,110,32,116,101,115,...>>,...]) in 'Elixir.Amrita.Formatter.Progress':print_test_failure/2 line 179
2013-12-13 16:02:53.907 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad argument in call to io:put_chars(<0.23.0>, unicode, [<<32,32,49,41,32,116,101,115,116,32,105,110,116,101,103,114,97,116,105,111,110,32,116,101,115,...>>,...]) in 'Elixir.Amrita.Formatter.Progress':print_test_failure/2 line 179 in gen_server:terminate/6 line 744
2013-12-13 16:03:35.557 [error] <0.152.0> gen_server <0.152.0> terminated with reason: bad argument in call to io:put_chars(<0.23.0>, unicode, [<<32,32,49,41,32,116,101,115,116,32,105,110,116,101,103,114,97,116,105,111,110,32,116,101,115,...>>,...]) in 'Elixir.Amrita.Formatter.Progress':print_test_failure/2 line 179
2013-12-13 16:03:35.557 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad argument in call to io:put_chars(<0.23.0>, unicode, [<<32,32,49,41,32,116,101,115,116,32,105,110,116,101,103,114,97,116,105,111,110,32,116,101,115,...>>,...]) in 'Elixir.Amrita.Formatter.Progress':print_test_failure/2 line 179 in gen_server:terminate/6 line 744
2013-12-13 16:03:52.000 [error] <0.159.0> gen_server <0.159.0> terminated with reason: {'module could not be loaded',[{send,send_pid,[{send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}],[]},{'Elixir.Yugioh.System.Room',handle,3,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/system/room.ex"},{line,34}]},{'Elixir.Yugioh.Player',handle_call,3,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,30}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 16:03:52.001 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 2 neighbours exited with reason: call to undefined function send:send_pid({send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}) in gen_server:terminate/6 line 744
2013-12-13 16:03:52.001 [error] <0.138.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.158.0> exit with reason call to undefined function send:send_pid({send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}) in context child_terminated
2013-12-13 16:04:01.376 [error] <0.159.0> gen_server <0.159.0> terminated with reason: {'module could not be loaded',[{send,send_pid,[{send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}],[]},{'Elixir.Yugioh.System.Room',handle,3,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/system/room.ex"},{line,34}]},{'Elixir.Yugioh.Player',handle_call,3,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,30}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 16:04:01.376 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 2 neighbours exited with reason: call to undefined function send:send_pid({send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}) in gen_server:terminate/6 line 744
2013-12-13 16:04:01.376 [error] <0.138.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.158.0> exit with reason call to undefined function send:send_pid({send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}) in context child_terminated
2013-12-13 18:33:06.525 [error] <0.159.0> gen_server <0.159.0> terminated with reason: {'module could not be loaded',[{send,id,[{send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}],[]},{'Elixir.Yugioh.Player',handle_cast,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,62}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 18:33:06.526 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 1 neighbours exited with reason: call to undefined function send:id({send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}) in gen_server:terminate/6 line 744
2013-12-13 18:41:05.349 [error] <0.159.0> gen_server <0.159.0> terminated with reason: {'module could not be loaded',[{send,id,[{send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}],[]},{'Elixir.Yugioh.Player',handle_cast,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,62}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 18:41:05.350 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 1 neighbours exited with reason: call to undefined function send:id({send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}) in gen_server:terminate/6 line 744
2013-12-13 18:44:53.628 [error] <0.159.0> gen_server <0.159.0> terminated with reason: {'module could not be loaded',[{send,id,[{send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}],[]},{'Elixir.Yugioh.Player',handle_cast,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,62}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 18:44:58.863 [error] <0.159.0> gen_server <0.159.0> terminated with reason: {'module could not be loaded',[{send,id,[{send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}],[]},{'Elixir.Yugioh.Player',handle_cast,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,62}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 18:44:58.863 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 1 neighbours exited with reason: call to undefined function send:id({send,<<0,20,42,249,0,1,0,0,0,1,0,6,49,50,51,52,53,54,0,1>>}) in gen_server:terminate/6 line 744
2013-12-13 19:01:50.819 [error] <0.259.0> gen_server <0.259.0> terminated with reason: {'module could not be loaded',[{ok,id,[],[]},{'Elixir.Yugioh.Player',handle_cast,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,50}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 19:05:00.554 [error] <0.147.0> gen_server <0.147.0> terminated with reason: {'module could not be loaded',[{ok,id,[],[]},{'Elixir.Yugioh.Player',handle_cast,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,50}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 19:05:00.554 [error] <0.147.0> CRASH REPORT Process <0.147.0> with 0 neighbours exited with reason: call to undefined function ok:id() in gen_server:terminate/6 line 744
2013-12-13 19:08:09.767 [error] <0.149.0> gen_server <0.149.0> terminated with reason: {'module could not be loaded',[{ok,id,[],[]},{'Elixir.Yugioh.Player',handle_cast,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,50}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 19:08:09.767 [error] <0.149.0> CRASH REPORT Process <0.149.0> with 0 neighbours exited with reason: call to undefined function ok:id() in gen_server:terminate/6 line 744
2013-12-13 19:09:39.348 [error] <0.204.0> gen_server <0.204.0> terminated with reason: {'module could not be loaded',[{ok,id,[],[]},{'Elixir.Yugioh.Player',terminate,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,62}]},{gen_server,terminate,6,[{file,"gen_server.erl"},{line,719}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 19:09:39.348 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: call to undefined function ok:id() in gen_server:terminate/6 line 722
2013-12-13 19:12:02.570 [error] <0.204.0> gen_server <0.204.0> terminated with reason: {'module could not be loaded',[{ok,id,[],[]},{'Elixir.Yugioh.Player',handle_cast,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,50}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-13 19:12:02.570 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: call to undefined function ok:id() in gen_server:terminate/6 line 744
2013-12-14 16:10:34.919 [error] <0.152.0> gen_server <0.152.0> terminated with reason: bad argument in call to io:put_chars(<0.23.0>, unicode, [<<32,32,49,41,32,116,101,115,116,32,105,110,116,101,103,114,97,116,105,111,110,32,116,101,115,...>>,...]) in 'Elixir.Amrita.Formatter.Progress':print_test_failure/2 line 179
2013-12-14 16:10:34.919 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad argument in call to io:put_chars(<0.23.0>, unicode, [<<32,32,49,41,32,116,101,115,116,32,105,110,116,101,103,114,97,116,105,111,110,32,116,101,115,...>>,...]) in 'Elixir.Amrita.Formatter.Progress':print_test_failure/2 line 179 in gen_server:terminate/6 line 744
2013-12-14 16:11:22.113 [error] <0.152.0> gen_server <0.152.0> terminated with reason: bad argument in call to io:put_chars(<0.23.0>, unicode, [<<32,32,49,41,32,116,101,115,116,32,105,110,116,101,103,114,97,116,105,111,110,32,116,101,115,...>>,...]) in 'Elixir.Amrita.Formatter.Progress':print_test_failure/2 line 179
2013-12-14 16:11:22.113 [error] <0.152.0> CRASH REPORT Process <0.152.0> with 0 neighbours exited with reason: bad argument in call to io:put_chars(<0.23.0>, unicode, [<<32,32,49,41,32,116,101,115,116,32,105,110,116,101,103,114,97,116,105,111,110,32,116,101,115,...>>,...]) in 'Elixir.Amrita.Formatter.Progress':print_test_failure/2 line 179 in gen_server:terminate/6 line 744
2013-12-15 23:14:54.743 [error] emulator Error in process <0.207.0> with exit value: {undef,[{nil,value,[],[]},{'Elixir.Yugioh.System.Login',enter_game,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/system/login.ex"},{line,86}]},{'Elixir.Yugioh.Acceptor.Acceptor',route_message,4,[{file,"/Users/sail/elix... 


2013-12-15 23:14:54.744 [error] <0.188.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.207.0> exit with reason call to undefined function nil:value() in context child_terminated
2013-12-15 23:16:14.312 [error] emulator Error in process <0.207.0> with exit value: {undef,[{nil,value,[],[]},{'Elixir.Yugioh.System.Login',enter_game,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/system/login.ex"},{line,85}]},{'Elixir.Yugioh.Acceptor.Acceptor',route_message,4,[{file,"/Users/sail/elix... 


2013-12-15 23:16:14.312 [error] <0.188.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.207.0> exit with reason call to undefined function nil:value() in context child_terminated
2013-12-15 23:17:26.087 [error] emulator Error in process <0.207.0> with exit value: {undef,[{nil,value,[],[]},{'Elixir.Yugioh.System.Login',enter_game,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/system/login.ex"},{line,85}]},{'Elixir.Yugioh.Acceptor.Acceptor',route_message,4,[{file,"/Users/sail/elix... 


2013-12-15 23:17:26.087 [error] <0.188.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.207.0> exit with reason call to undefined function nil:value() in context child_terminated
2013-12-15 23:30:04.231 [error] <0.159.0> gen_server <0.159.0> terminated with reason: {'module could not be loaded',[{'Elixir.PT',pack_string,[<<"room">>],[]},{'Elixir.RecordHelper',decode_room_info,1,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/records.ex"},{line,21}]},{'Elixir.Yugioh.Proto.PT11',write,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/proto/pt_11.ex"},{line,19}]},{'Elixir.Yugioh.System.Room',handle,3,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/system/room.ex"},{line,11}]},{'Elixir.Yugioh.Player',handle_call,3,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/playe..."},...]},...]}
2013-12-15 23:30:04.231 [error] <0.159.0> CRASH REPORT Process <0.159.0> with 1 neighbours exited with reason: call to undefined function 'Elixir.PT':pack_string(<<"room">>) in gen_server:terminate/6 line 744
2013-12-15 23:30:04.231 [error] <0.138.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.156.0> exit with reason call to undefined function 'Elixir.PT':pack_string(<<"room">>) in context child_terminated
2013-12-15 23:31:38.772 [error] <0.262.0> gen_server <0.262.0> terminated with reason: bad argument in 'Elixir.Yugioh.Proto':pack_string/1 line 19
2013-12-15 23:31:38.772 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 1 neighbours exited with reason: bad argument in 'Elixir.Yugioh.Proto':pack_string/1 line 19 in gen_server:terminate/6 line 744
2013-12-15 23:31:38.772 [error] <0.242.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.260.0> exit with reason bad argument in 'Elixir.Yugioh.Proto':pack_string/1 line 19 in context child_terminated
2013-12-15 23:33:35.116 [error] <0.276.0> gen_server <0.276.0> terminated with reason: bad argument in 'Elixir.RecordHelper':decode_room_info/1 line 21
2013-12-15 23:33:35.116 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 1 neighbours exited with reason: bad argument in 'Elixir.RecordHelper':decode_room_info/1 line 21 in gen_server:terminate/6 line 744
2013-12-15 23:33:35.116 [error] <0.256.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.274.0> exit with reason bad argument in 'Elixir.RecordHelper':decode_room_info/1 line 21 in context child_terminated
2013-12-15 23:34:42.240 [error] <0.262.0> gen_server <0.262.0> terminated with reason: bad argument in 'Elixir.Yugioh.Proto.PT11':write/2 line 19
2013-12-15 23:34:42.240 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 1 neighbours exited with reason: bad argument in 'Elixir.Yugioh.Proto.PT11':write/2 line 19 in gen_server:terminate/6 line 744
2013-12-15 23:34:42.241 [error] <0.242.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.260.0> exit with reason bad argument in 'Elixir.Yugioh.Proto.PT11':write/2 line 19 in context child_terminated
2013-12-15 23:48:34.309 [error] <0.277.0> gen_server <0.277.0> terminated with reason: no function clause matching 'Elixir.Yugioh.Proto.PT11':write(11002, 1) line 18
2013-12-15 23:48:34.309 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 1 neighbours exited with reason: no function clause matching 'Elixir.Yugioh.Proto.PT11':write(11002, 1) line 18 in gen_server:terminate/6 line 744
2013-12-15 23:48:34.309 [error] <0.256.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.275.0> exit with reason no function clause matching 'Elixir.Yugioh.Proto.PT11':write(11002, 1) line 18 in context child_terminated
2013-12-16 21:29:28.909 [error] <0.233.0> CRASH REPORT Process <0.233.0> with 0 neighbours exited with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in gen_server:init_it/6 line 328
2013-12-16 21:29:28.910 [error] <0.228.0> Supervisor {<0.228.0>,'Elixir.Yugioh.Supervisor'} had child 'Elixir.Yugioh.Repo' started with 'Elixir.Yugioh.Repo':start_link() at undefined exit with reason no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in context start_error
2013-12-16 21:29:28.910 [error] <0.234.0> gen_server <0.234.0> terminated with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236
2013-12-16 21:29:28.910 [error] <0.234.0> CRASH REPORT Process <0.234.0> with 0 neighbours exited with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in gen_server:terminate/6 line 744
2013-12-16 21:29:28.910 [error] <0.226.0> CRASH REPORT Process <0.226.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Yugioh.Repo',{{badmatch,{error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}}},[{poolboy,new_worker,1,[{file,"src/poolboy.erl"},{line,236}]},{poolboy,prepopulate,3,[{file,"src/poolboy.erl"},{line,257}]},{poolboy,init,3,[{file,"src/poolboy.erl"},{line,120}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}}},{'Elixir.Yugioh',start,[normal,[]]}} in application_master:init/4 line 133
2013-12-16 21:30:47.403 [error] <0.158.0> gen_server <0.158.0> terminated with reason: fun called with wrong arity of 1 instead of 2 in 'Elixir.Enum':'-map/2-lc$^0/1-0-'/2 line 680
2013-12-16 21:30:47.403 [error] <0.158.0> CRASH REPORT Process <0.158.0> with 1 neighbours exited with reason: fun called with wrong arity of 1 instead of 2 in 'Elixir.Enum':'-map/2-lc$^0/1-0-'/2 line 680 in gen_server:terminate/6 line 744
2013-12-16 21:30:47.403 [error] <0.138.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.156.0> exit with reason fun called with wrong arity of 1 instead of 2 in 'Elixir.Enum':'-map/2-lc$^0/1-0-'/2 line 680 in context child_terminated
2013-12-16 21:38:41.974 [error] <0.262.0> gen_server <0.262.0> terminated with reason: call to undefined function 'Elixir.Yugioh.Player':player_state/0 from 'Elixir.RecordHelper':'-encode_room_info/1-fun-0-'/2 line 42
2013-12-16 21:38:41.974 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 1 neighbours exited with reason: call to undefined function 'Elixir.Yugioh.Player':player_state() in gen_server:terminate/6 line 744
2013-12-16 21:38:41.975 [error] <0.242.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.260.0> exit with reason call to undefined function 'Elixir.Yugioh.Player':player_state() in context child_terminated
2013-12-16 21:40:56.994 [error] <0.262.0> gen_server <0.262.0> terminated with reason: {{function_clause,[{gen,call,[{<0.262.0>,#Ref<0.0.0.2835>},'$gen_call',player_state,5000],[{file,"gen.erl"},{line,147}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,176}]},{'Elixir.RecordHelper','-encode_room_info/1-fun-0-',2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/records.ex"},{line,42}]},{'Elixir.Enum','-map/2-lc$^0/1-0-',2,[{file,"/private/tmp/elixir-pl3M/elixir-0.11.2/lib/elixir/lib/enum.ex"},{line,680}]},{'Elixir.RecordHelper',encode_room_info,1,[{file,"/Users/sail/elixir/y..."},...]},...]},...}
2013-12-16 21:40:56.994 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 1 neighbours exited with reason: {{function_clause,[{gen,call,[{<0.262.0>,#Ref<0.0.0.2835>},'$gen_call',player_state,5000],[{file,"gen.erl"},{line,147}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,176}]},{'Elixir.RecordHelper','-encode_room_info/1-fun-0-',2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/records.ex"},{line,42}]},{'Elixir.Enum','-map/2-lc$^0/1-0-',2,[{file,"/private/tmp/elixir-pl3M/elixir-0.11.2/lib/elixir/lib/enum.ex"},{line,680}]},{'Elixir.RecordHelper',encode_room_info,1,[{file,"/Users/sail/elixir/y..."},...]},...]},...} in gen_server:terminate/6 line 744
2013-12-16 21:40:56.995 [error] <0.242.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.260.0> exit with reason {{function_clause,[{gen,call,[{<0.262.0>,#Ref<0.0.0.2835>},'$gen_call',player_state,5000],[{file,"gen.erl"},{line,147}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,176}]},{'Elixir.RecordHelper','-encode_room_info/1-fun-0-',2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/records.ex"},{line,42}]},{'Elixir.Enum','-map/2-lc$^0/1-0-',2,[{file,"/private/tmp/elixir-pl3M/elixir-0.11.2/lib/elixir/lib/enum.ex"},{line,680}]},{'Elixir.RecordHelper',encode_room_info,1,[{file,"/Users/sail/elixir/y..."},...]},...]},...} in context child_terminated
2013-12-16 22:19:50.095 [error] <0.262.0> gen_server <0.262.0> terminated with reason: {{function_clause,[{gen,call,[{<0.262.0>,#Ref<0.0.0.2834>},'$gen_call',player_state,5000],[{file,"gen.erl"},{line,147}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,176}]},{'Elixir.Yugioh.Player',player_state,1,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,73}]},{'Elixir.RecordHelper','-encode_room_info/1-fun-0-',2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/records.ex"},{line,42}]},{'Elixir.Enum','-map/2-lc$^0/1-0-',2,[{file,"/private/tmp/elixir-pl3M/elixir-0.11.2/..."},...]},...]},...}
2013-12-16 22:19:50.095 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 1 neighbours exited with reason: {{function_clause,[{gen,call,[{<0.262.0>,#Ref<0.0.0.2834>},'$gen_call',player_state,5000],[{file,"gen.erl"},{line,147}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,176}]},{'Elixir.Yugioh.Player',player_state,1,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,73}]},{'Elixir.RecordHelper','-encode_room_info/1-fun-0-',2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/records.ex"},{line,42}]},{'Elixir.Enum','-map/2-lc$^0/1-0-',2,[{file,"/private/tmp/elixir-pl3M/elixir-0.11.2/..."},...]},...]},...} in gen_server:terminate/6 line 744
2013-12-16 22:19:50.096 [error] <0.242.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.260.0> exit with reason {{function_clause,[{gen,call,[{<0.262.0>,#Ref<0.0.0.2834>},'$gen_call',player_state,5000],[{file,"gen.erl"},{line,147}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,176}]},{'Elixir.Yugioh.Player',player_state,1,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,73}]},{'Elixir.RecordHelper','-encode_room_info/1-fun-0-',2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/records.ex"},{line,42}]},{'Elixir.Enum','-map/2-lc$^0/1-0-',2,[{file,"/private/tmp/elixir-pl3M/elixir-0.11.2/..."},...]},...]},...} in context child_terminated
2013-12-16 22:27:59.556 [error] <0.262.0> gen_server <0.262.0> terminated with reason: {timeout,{gen_server,call,[<0.262.0>,player_state]}}
2013-12-16 22:27:59.556 [error] <0.262.0> CRASH REPORT Process <0.262.0> with 1 neighbours exited with reason: {timeout,{gen_server,call,[<0.262.0>,player_state]}} in gen_server:terminate/6 line 744
2013-12-16 22:27:59.556 [error] <0.242.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.260.0> exit with reason {timeout,{gen_server,call,[<0.262.0>,player_state]}} in context child_terminated
2013-12-16 22:43:19.943 [error] <0.138.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.156.0> exit with reason {timeout,{gen_server,call,[<0.159.0>,{<<"SOCKET_EVENT">>,11000,{create_room,<<"room">>,1}}]}} in context child_terminated
