2013-12-17 10:20:47.205 [error] <0.312.0> gen_server <0.312.0> terminated with reason: call to undefined function 'Elixir.Yugioh.Proto':encode_player_brief_info/1 from 'Elixir.RecordHelper':'-encode_room_info/1-fun-0-'/2 line 42
2013-12-17 10:20:47.205 [error] <0.312.0> CRASH REPORT Process <0.312.0> with 1 neighbours exited with reason: call to undefined function 'Elixir.Yugioh.Proto':encode_player_brief_info(<0.312.0>) in gen_server:terminate/6 line 744
2013-12-17 10:20:47.205 [error] <0.292.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.310.0> exit with reason call to undefined function 'Elixir.Yugioh.Proto':encode_player_brief_info(<0.312.0>) in context child_terminated
2013-12-17 10:21:32.453 [error] <0.269.0> gen_server <0.269.0> terminated with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 19
2013-12-17 10:21:32.453 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 19 in gen_server:terminate/6 line 744
2013-12-17 10:21:32.453 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 19 in context child_terminated
2013-12-17 10:23:06.742 [error] <0.269.0> gen_server <0.269.0> terminated with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 19
2013-12-17 10:23:06.742 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 19 in gen_server:terminate/6 line 744
2013-12-17 10:23:06.743 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 19 in context child_terminated
2013-12-17 10:24:26.682 [error] <0.269.0> gen_server <0.269.0> terminated with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21
2013-12-17 10:24:26.683 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in gen_server:terminate/6 line 744
2013-12-17 10:24:26.683 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in context child_terminated
2013-12-17 10:25:20.497 [error] <0.269.0> gen_server <0.269.0> terminated with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21
2013-12-17 10:25:20.497 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in gen_server:terminate/6 line 744
2013-12-17 10:25:20.498 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in context child_terminated
2013-12-17 10:26:04.998 [error] <0.269.0> gen_server <0.269.0> terminated with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21
2013-12-17 10:26:04.999 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in gen_server:terminate/6 line 744
2013-12-17 10:26:04.999 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in context child_terminated
2013-12-17 10:33:42.336 [error] <0.269.0> gen_server <0.269.0> terminated with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21
2013-12-17 10:33:42.336 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in gen_server:terminate/6 line 744
2013-12-17 10:33:42.337 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in context child_terminated
2013-12-17 10:36:32.965 [error] <0.269.0> gen_server <0.269.0> terminated with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21
2013-12-17 10:36:32.965 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in gen_server:terminate/6 line 744
2013-12-17 10:36:32.966 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in context child_terminated
2013-12-17 10:39:09.723 [error] <0.269.0> gen_server <0.269.0> terminated with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21
2013-12-17 10:39:09.723 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in gen_server:terminate/6 line 744
2013-12-17 10:39:09.724 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason bad argument in call to erlang:apply(<0.269.0>, id, []) in 'Elixir.RecordHelper':encode_player_brief_info/1 line 21 in context child_terminated
2013-12-17 16:33:27.392 [error] <0.145.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.164.0> exit with reason {timeout,{gen_server,call,[<0.165.0>,{<<"SOCKET_EVENT">>,11002,{enter_room,1}}]}} in context child_terminated
2013-12-17 16:37:03.178 [error] <0.270.0> gen_server <0.270.0> terminated with reason: {timeout,{gen_server,call,[<0.270.0>,player_state]}}
2013-12-17 16:37:03.179 [error] <0.270.0> CRASH REPORT Process <0.270.0> with 1 neighbours exited with reason: {timeout,{gen_server,call,[<0.270.0>,player_state]}} in gen_server:terminate/6 line 744
2013-12-17 16:37:03.179 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.268.0> exit with reason {timeout,{gen_server,call,[<0.270.0>,player_state]}} in context child_terminated
2013-12-17 16:37:51.111 [error] <0.270.0> gen_server <0.270.0> terminated with reason: {timeout,{gen_server,call,[<0.270.0>,player_state]}}
2013-12-17 16:37:51.111 [error] <0.270.0> CRASH REPORT Process <0.270.0> with 1 neighbours exited with reason: {timeout,{gen_server,call,[<0.270.0>,player_state]}} in gen_server:terminate/6 line 744
2013-12-17 16:37:51.111 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.268.0> exit with reason {timeout,{gen_server,call,[<0.270.0>,player_state]}} in context child_terminated
2013-12-17 16:39:08.049 [error] <0.270.0> gen_server <0.270.0> terminated with reason: {timeout,{gen_server,call,[<0.270.0>,player_state]}}
2013-12-17 16:39:08.049 [error] <0.270.0> CRASH REPORT Process <0.270.0> with 1 neighbours exited with reason: {timeout,{gen_server,call,[<0.270.0>,player_state]}} in gen_server:terminate/6 line 744
2013-12-17 16:39:08.050 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.268.0> exit with reason {timeout,{gen_server,call,[<0.270.0>,player_state]}} in context child_terminated
2013-12-17 17:17:20.627 [error] <0.269.0> gen_server <0.269.0> terminated with reason: {'module could not be loaded',[{'Elixir.Yugioh.ProtoPT11',write,[11003,[2,{'Elixir.PlayerState',8,<<"xqy">>,1,1,3000,0,0,[1,2,3,4],#Port<0.8735>,true}]],[]},{'Elixir.Yugioh.Player',handle_info,2,[{file,"/Users/sail/elixir/yugioh/lib/yugioh/player.ex"},{line,61}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,604}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
2013-12-17 17:17:20.627 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 1 neighbours exited with reason: call to undefined function 'Elixir.Yugioh.ProtoPT11':write(11003, [2,{'Elixir.PlayerState',8,<<"xqy">>,1,1,3000,0,0,[1,2,3,4],#Port<0.8735>,true}]) in gen_server:terminate/6 line 744
2013-12-17 17:17:20.627 [error] <0.249.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.267.0> exit with reason call to undefined function 'Elixir.Yugioh.ProtoPT11':write(11003, [2,{'Elixir.PlayerState',8,<<"xqy">>,1,1,3000,0,0,[1,2,3,4],#Port<0.8735>,true}]) in context child_terminated
2013-12-18 15:07:54.243 [error] <0.129.0> CRASH REPORT Process <0.129.0> with 0 neighbours exited with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in gen_server:init_it/6 line 328
2013-12-18 15:07:54.244 [error] <0.124.0> Supervisor {<0.124.0>,'Elixir.Yugioh.Supervisor'} had child 'Elixir.Yugioh.Repo' started with 'Elixir.Yugioh.Repo':start_link() at undefined exit with reason no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in context start_error
2013-12-18 15:07:54.244 [error] <0.130.0> gen_server <0.130.0> terminated with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236
2013-12-18 15:07:54.244 [error] <0.130.0> CRASH REPORT Process <0.130.0> with 0 neighbours exited with reason: no match of right hand value {error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}} in poolboy:new_worker/1 line 236 in gen_server:terminate/6 line 744
2013-12-18 15:07:54.244 [error] <0.122.0> CRASH REPORT Process <0.122.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Yugioh.Repo',{{badmatch,{error,{'Elixir.Postgrex.Error','__exception__',nil,<<"tcp connect: econnrefused">>}}},[{poolboy,new_worker,1,[{file,"src/poolboy.erl"},{line,236}]},{poolboy,prepopulate,3,[{file,"src/poolboy.erl"},{line,257}]},{poolboy,init,3,[{file,"src/poolboy.erl"},{line,120}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}}},{'Elixir.Yugioh',start,[normal,[]]}} in application_master:init/4 line 133
2013-12-18 15:08:01.001 [error] <0.134.0> gen_server <0.134.0> terminated with reason: no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90
2013-12-18 15:08:01.002 [error] <0.134.0> CRASH REPORT Process <0.134.0> with 0 neighbours exited with reason: no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90 in gen_server:terminate/6 line 744
2013-12-18 15:08:01.002 [error] <0.130.0> Supervisor {<0.130.0>,poolboy_sup} had child 'Elixir.Postgrex.Connection' started with {'Elixir.Postgrex.Connection',start_link,undefined} at <0.134.0> exit with reason no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90 in context child_terminated
2013-12-18 15:08:01.003 [error] <0.129.0> CRASH REPORT Process <0.129.0> with 1 neighbours exited with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in gen_server:init_it/6 line 328
2013-12-18 15:08:01.003 [error] <0.124.0> Supervisor {<0.124.0>,'Elixir.Yugioh.Supervisor'} had child 'Elixir.Yugioh.Repo' started with 'Elixir.Yugioh.Repo':start_link() at undefined exit with reason no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in context start_error
2013-12-18 15:08:01.004 [error] <0.130.0> Supervisor {<0.130.0>,poolboy_sup} had child 'Elixir.Postgrex.Connection' started with 'Elixir.Postgrex.Connection':start_link([{port,5432},{decoder,#Fun<Elixir.Ecto.Adapters.Postgres.14.100735558>},{password,<<"sailtsao">>},...]) at undefined exit with reason no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in context shutdown_error
2013-12-18 15:08:01.004 [error] <0.130.0> gen_server <0.130.0> terminated with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236
2013-12-18 15:08:01.005 [error] <0.130.0> CRASH REPORT Process <0.130.0> with 0 neighbours exited with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in gen_server:terminate/6 line 744
2013-12-18 15:08:01.005 [error] <0.122.0> CRASH REPORT Process <0.122.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Yugioh.Repo',{{badmatch,{error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,...},...]},...}}}},...}}},...} in application_master:init/4 line 133
2013-12-18 15:08:06.846 [error] <0.134.0> gen_server <0.134.0> terminated with reason: no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90
2013-12-18 15:08:06.846 [error] <0.134.0> CRASH REPORT Process <0.134.0> with 0 neighbours exited with reason: no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90 in gen_server:terminate/6 line 744
2013-12-18 15:08:06.846 [error] <0.130.0> Supervisor {<0.130.0>,poolboy_sup} had child 'Elixir.Postgrex.Connection' started with {'Elixir.Postgrex.Connection',start_link,undefined} at <0.134.0> exit with reason no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90 in context child_terminated
2013-12-18 15:08:06.847 [error] <0.129.0> CRASH REPORT Process <0.129.0> with 1 neighbours exited with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in gen_server:init_it/6 line 328
2013-12-18 15:08:06.847 [error] <0.124.0> Supervisor {<0.124.0>,'Elixir.Yugioh.Supervisor'} had child 'Elixir.Yugioh.Repo' started with 'Elixir.Yugioh.Repo':start_link() at undefined exit with reason no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in context start_error
2013-12-18 15:08:06.848 [error] <0.130.0> Supervisor {<0.130.0>,poolboy_sup} had child 'Elixir.Postgrex.Connection' started with 'Elixir.Postgrex.Connection':start_link([{port,5432},{decoder,#Fun<Elixir.Ecto.Adapters.Postgres.14.100735558>},{password,<<"sailtsao">>},...]) at undefined exit with reason no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in context shutdown_error
2013-12-18 15:08:06.849 [error] <0.130.0> gen_server <0.130.0> terminated with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236
2013-12-18 15:08:06.849 [error] <0.130.0> CRASH REPORT Process <0.130.0> with 0 neighbours exited with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in gen_server:terminate/6 line 744
2013-12-18 15:08:06.850 [error] <0.122.0> CRASH REPORT Process <0.122.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Yugioh.Repo',{{badmatch,{error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,...},...]},...}}}},...}}},...} in application_master:init/4 line 133
2013-12-18 15:08:17.626 [error] <0.134.0> gen_server <0.134.0> terminated with reason: no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90
2013-12-18 15:08:17.627 [error] <0.134.0> CRASH REPORT Process <0.134.0> with 0 neighbours exited with reason: no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90 in gen_server:terminate/6 line 744
2013-12-18 15:08:17.627 [error] <0.130.0> Supervisor {<0.130.0>,poolboy_sup} had child 'Elixir.Postgrex.Connection' started with {'Elixir.Postgrex.Connection',start_link,undefined} at <0.134.0> exit with reason no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90 in context child_terminated
2013-12-18 15:08:17.628 [error] <0.129.0> CRASH REPORT Process <0.129.0> with 1 neighbours exited with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in gen_server:init_it/6 line 328
2013-12-18 15:08:17.629 [error] <0.124.0> Supervisor {<0.124.0>,'Elixir.Yugioh.Supervisor'} had child 'Elixir.Yugioh.Repo' started with 'Elixir.Yugioh.Repo':start_link() at undefined exit with reason no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in context start_error
2013-12-18 15:08:17.629 [error] <0.130.0> Supervisor {<0.130.0>,poolboy_sup} had child 'Elixir.Postgrex.Connection' started with 'Elixir.Postgrex.Connection':start_link([{port,5432},{decoder,#Fun<Elixir.Ecto.Adapters.Postgres.14.100735558>},{password,<<"sailtsao">>},...]) at undefined exit with reason no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in context shutdown_error
2013-12-18 15:08:17.630 [error] <0.130.0> gen_server <0.130.0> terminated with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236
2013-12-18 15:08:17.630 [error] <0.130.0> CRASH REPORT Process <0.130.0> with 0 neighbours exited with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in gen_server:terminate/6 line 744
2013-12-18 15:08:17.631 [error] <0.122.0> CRASH REPORT Process <0.122.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Yugioh.Repo',{{badmatch,{error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,...},...]},...}}}},...}}},...} in application_master:init/4 line 133
2013-12-18 15:09:52.760 [error] <0.281.0> gen_server <0.281.0> terminated with reason: no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90
2013-12-18 15:09:52.760 [error] <0.281.0> CRASH REPORT Process <0.281.0> with 0 neighbours exited with reason: no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90 in gen_server:terminate/6 line 744
2013-12-18 15:09:52.761 [error] <0.277.0> Supervisor {<0.277.0>,poolboy_sup} had child 'Elixir.Postgrex.Connection' started with {'Elixir.Postgrex.Connection',start_link,undefined} at <0.281.0> exit with reason no function clause matching inet_tcp:do_connect({0,0,0,0,0,0,0,1}, 5432, [{active,once},{packet,raw},binary], infinity) line 90 in context child_terminated
2013-12-18 15:09:52.761 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 1 neighbours exited with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in gen_server:init_it/6 line 328
2013-12-18 15:09:52.762 [error] <0.271.0> Supervisor {<0.271.0>,'Elixir.Yugioh.Supervisor'} had child 'Elixir.Yugioh.Repo' started with 'Elixir.Yugioh.Repo':start_link() at undefined exit with reason no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in context start_error
2013-12-18 15:09:52.763 [error] <0.277.0> Supervisor {<0.277.0>,poolboy_sup} had child 'Elixir.Postgrex.Connection' started with 'Elixir.Postgrex.Connection':start_link([{port,5432},{decoder,#Fun<Elixir.Ecto.Adapters.Postgres.14.100735558>},{password,<<"sailtsao">>},...]) at undefined exit with reason no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in context shutdown_error
2013-12-18 15:09:52.763 [error] <0.277.0> gen_server <0.277.0> terminated with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236
2013-12-18 15:09:52.764 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: no match of right hand value {error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,...}]},...}}} in poolboy:new_worker/1 line 236 in gen_server:terminate/6 line 744
2013-12-18 15:09:52.764 [error] <0.269.0> CRASH REPORT Process <0.269.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Yugioh.Repo',{{badmatch,{error,{'EXIT',{{function_clause,[{inet_tcp,do_connect,[{0,0,0,0,0,0,0,1},5432,[{active,once},{packet,raw},binary],infinity],[{file,"inet_tcp.erl"},{line,90}]},{gen_tcp,try_connect,6,[{file,"gen_tcp.erl"},{line,163}]},{gen_tcp,connect,4,[{file,"gen_tcp.erl"},{line,141}]},{'Elixir.Postgrex.Connection',handle_call,3,[{file,"/Users/sail/elixir/yugioh/deps/postgrex/lib/postgrex/connection.ex"},{line,256}]},{gen_server,handle_msg,...},...]},...}}}},...}}},...} in application_master:init/4 line 133
2013-12-18 15:30:36.585 [error] <0.215.0> gen_server 'Elixir.Yugioh.Singleton.Room' terminated with reason: no function clause matching 'Elixir.HashDict':drop({'Elixir.HashDict',2,[[1|<0.245.0>],[2|<0.246.0>]]}, 1) line 11
2013-12-18 15:30:36.585 [error] <0.215.0> CRASH REPORT Process 'Elixir.Yugioh.Singleton.Room' with 0 neighbours exited with reason: no function clause matching 'Elixir.HashDict':drop({'Elixir.HashDict',2,[[1|<0.245.0>],[2|<0.246.0>]]}, 1) line 11 in gen_server:terminate/6 line 744
2013-12-18 15:33:22.190 [error] <0.215.0> gen_server 'Elixir.Yugioh.Singleton.Room' terminated with reason: bad return value: [{reply,ok,{'Elixir.RoomInfo',1,wait,<<"room">>,1,<0.245.0>,{'Elixir.HashDict',1,[[2|<0.246.0>]]}}},nil]
2013-12-18 15:33:22.191 [error] <0.215.0> CRASH REPORT Process 'Elixir.Yugioh.Singleton.Room' with 0 neighbours exited with reason: bad return value: [{reply,ok,{'Elixir.RoomInfo',1,wait,<<"room">>,1,<0.245.0>,{'Elixir.HashDict',1,[[2|<0.246.0>]]}}},nil] in gen_server:terminate/6 line 744
2013-12-18 16:01:46.393 [error] <0.246.0> gen_server <0.246.0> terminated with reason: {timeout,{gen_server,call,[<0.246.0>,player_state]}}
2013-12-18 16:01:46.393 [error] <0.246.0> CRASH REPORT Process <0.246.0> with 1 neighbours exited with reason: {timeout,{gen_server,call,[<0.246.0>,player_state]}} in gen_server:terminate/6 line 744
2013-12-18 16:01:46.394 [error] <0.225.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.244.0> exit with reason {timeout,{gen_server,call,[<0.246.0>,player_state]}} in context child_terminated
2013-12-18 16:08:40.337 [error] <0.143.0> gen_server <0.143.0> terminated with reason: call to undefined function 'Elixir.PlayerState':room_id/1 from 'Elixir.Yugioh.System.Room':handle/3 line 51
2013-12-18 16:08:40.338 [error] <0.143.0> CRASH REPORT Process <0.143.0> with 1 neighbours exited with reason: call to undefined function 'Elixir.PlayerState':room_id({'Elixir.PlayerState',8,<<"xqy">>,1,1,3000,0,0,[1,2,3,4],#Port<0.4988>,1}) in gen_server:terminate/6 line 744
2013-12-18 16:08:40.338 [error] <0.122.0> Supervisor 'Elixir.Yugioh.Acceptor.Supervisor' had child 'Elixir.Yugioh.Acceptor.Acceptor' started with {'Elixir.Yugioh.Acceptor.Acceptor',start_link,undefined} at <0.141.0> exit with reason call to undefined function 'Elixir.PlayerState':room_id({'Elixir.PlayerState',8,<<"xqy">>,1,1,3000,0,0,[1,2,3,4],#Port<0.4988>,1}) in context child_terminated
